### ISSUE TITLE
Inconsistency in header look between main page and docs pages

### ISSUE THREAD

**Issue by thephred** [crossplaneio/crossplaneio.github.io#18]
![image 1](https://user-images.githubusercontent.com/110422/51556373-dd33d000-1e2e-11e9-9d67-89258644d5bc.png)

![image 2](https://user-images.githubusercontent.com/110422/51556385-e3c24780-1e2e-11e9-97e7-98b32f927a2a.png)

Reported by @bassam

**Comment by rathpc** [comment]
I believe this is also related to the above mentioned issue:

![image](https://user-images.githubusercontent.com/5623579/56063187-91613a80-5d3c-11e9-8a6b-aa6d36744893.png)
