### ISSUE TITLE
Markdown tables render poorly.

### ISSUE THREAD

**Issue by negz** [crossplaneio/crossplaneio.github.io#26]
I'm experimenting with autogenerating API documentation for Crossplane using https://github.com/negz/crossdocs. Most of our website seems to be generated from markdown, so that's what I output. I'd like to use markdown tables, but these look unstyled in the HTML output:

<img width="1229" alt="output" src="https://user-images.githubusercontent.com/1049349/64902133-a0834600-d656-11e9-99e9-77d7c75eedc3.png">

As far as I can tell the markdown is being translated to a perfectly cromulent HTML `<table>`.

**Comment by negz** [comment]
Here's the markdown that generates the above screenshot:

```md
# cache.crossplane.io/v1alpha1 API Reference

Package v1alpha1 contains portable resource claims for caching services such as Redis clusters.

This API group contains the following resources:


## RedisCluster

A RedisCluster is a portable resource claim that may be satisfied by binding to a Redis managed resource such as a GCP CloudMemorystore instance or an AWS ReplicationGroup. Despite the name RedisCluster claims may bind to Redis managed resources that are a single node, or not in cluster mode.

Name | Type | Description
-----|------|------------
`metadata` | [meta/v1.ObjectMeta](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#objectmeta-v1-meta) | Kubernetes object metadata.
`spec` | [RedisClusterSpec](#RedisClusterSpec) | RedisClusterSpec specifies the desired state of a RedisCluster.
`status` | [v1alpha1.ResourceClaimStatus](../crossplane-runtime/core-crossplane-io-v1alpha1.md#resourceclaimstatus) | 



## RedisClusterClass

RedisClusterClass contains a namespace-scoped portable class for RedisCluster

Name | Type | Description
-----|------|------------
`metadata` | [meta/v1.ObjectMeta](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#objectmeta-v1-meta) | Kubernetes object metadata.


Also supports all fields of:

* [v1alpha1.PortableClass](../crossplane-runtime/core-crossplane-io-v1alpha1.md#portableclass)


## RedisClusterSpec

RedisClusterSpec specifies the desired state of a RedisCluster.

Appears in:

* [RedisCluster](#RedisCluster)

Name | Type | Description
-----|------|------------
`engineVersion` | string | EngineVersion specifies the desired Redis version.


Also supports all fields of:

* [v1alpha1.ResourceClaimSpec](../crossplane-runtime/core-crossplane-io-v1alpha1.md#resourceclaimspec)


This API documentation was generated by `crossdocs`.
```

**Comment by connorchan** [comment]
@negz — The existing table on this page seems to render very similarly to what you have in the screenshot: https://crossplane.io/docs/v0.2/install-crossplane.html

Did you have a certain design in mind for these/are there additional details you can provide for guidance on styling and design?

**Comment by negz** [comment]
@connorchan Ah, good find. I skimmed the docs for other tables but could not find anything.

* https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15
* https://knative.dev/docs/reference/eventing/

Above are two examples of similar generated API documentation from other Kubernetes-ey projects. We definitely don't need to match their style closely, but they're an example of what I'm going for. My main concern with the current rendering is that the columns and rows all kind of blend together; there's no borders, or alternating colors, or vertical padding to help distinguish one field from another. This isn't so bad in the previous screenshot, but it's a little more obvious below:

<img width="935" alt="whichiswhich" src="https://user-images.githubusercontent.com/1049349/64905911-6be1af80-d693-11e9-8df0-cd2cc44cf4a2.png">

**Comment by connorchan** [comment]
Yeah, these concerns definitely seem valid. This is going to require some input from Matt Heilman (who doesn't look to be part of this particular GitHub organization), which we may not be able to get for the Wednesday launch... @negz, do you have the proper permissions to add him?

**Comment by negz** [comment]
I don’t, @jbw976 @bassam do you?

**Comment by jbw976** [comment]
@connorchan happy to invite @mattheilman to the crossplane org, but what permissions does he need exactly?  This is a public repo that anyone can open PRs to, so I'd like to understand what he isn't able to do right now.

**Comment by mattheilman** [comment]
I don’t think I need to be added.

**Comment by connorchan** [comment]
I've added some padding to the <td> elements, which I'm including in the PR to update the homepage for the v0.3 launch
