### ISSUE TITLE
Crossplane blog: Link to the main site

### ISSUE THREAD

**Issue by soorena776** [crossplaneio/crossplaneio.github.io#31]
When opened a link to a crossplane blog (e.g. [this post]), one should be able to navigate the the main site (https://crossplane.io), possibly by having an option in the menu bar.

[this post]: https://blog.crossplane.io/crossplane-v0-4-new-rook-integration-supports-in-cluster-managed-database-alternatives-to-rds-cloudsql-and-azure-db/

**Comment by soorena776** [comment]
visibility: @jbw976

**Comment by jbw976** [comment]
good idea @soorena776! looks like you can add arbitrary links into the menu bar.  What do you think of the below screenshot?

![Screen Shot 2019-10-30 at 1 27 40 PM](https://user-images.githubusercontent.com/4313439/67896217-29781300-fb19-11e9-8087-ba1bf2b762c9.png)

Clicking "crossplane.io" in the menu bar takes you to https://crossplane.io.

**Comment by soorena776** [comment]
Yes, that's what I hoped for! Thanks!

**Comment by prasek** [comment]
looks good, thanks!

**Comment by jbw976** [comment]
Cool, it's live.  thanks for the suggestion @soorena776!
